### ISSUE TITLE
The GIT repository has JAVA code, the 

### ISSUE THREAD

**Issue by MarkusDatgloi** [googlecodelabs/complications-data-source#3]
https://developer.android.com/codelabs/data-providers  is written for Kotlin code and refers to GIT
 https://github.com/googlecodelabs/data-providers.git which is JAVA.

Nobody reviewed this project ?
This is so disappointing...

**Comment by codingjeremy** [comment]
Sorry, this was originally written in Java and somehow the PR wasn't merged. 

I merged it now, sorry!
