### ISSUE TITLE
Rendering issue on the codelab?

### ISSUE THREAD

**Issue by LouisCAD** [googlecodelabs/complications-data-source#5]
Hello, it seems like there's a rendering issue on https://developer.android.com/codelabs/data-providers

See the annotated screenshot below:

<img width="1119" alt="Screenshot 2021-11-29 at 00 16 30" src="https://user-images.githubusercontent.com/6975237/143790345-0528206a-558b-4594-80cd-b7715bd668e1.png">

**Comment by codingjeremy** [comment]
Thanks for the catch! This was fixed earlier this year, so we should be all set.
